# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='question_text',
            new_name='stu_name',
        ),
    ]
