# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170125_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_family',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stu_password',
            field=models.CharField(default='123456', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stu_phone',
            field=models.CharField(default='0911191700', max_length=200),
            preserve_default=False,
        ),
    ]
